import type { ToolPricing } from "./models.js";

export const PRICING_DATABASE: ToolPricing[] = [
  { tool_id: "cursor", name: "Cursor", category: "coding", url: "https://cursor.com", tiers: [{ name: "Hobby", price_monthly: 0, price_annual: 0, features: ["Basic AI coding assistance"], limits: "Individual free usage" }, { name: "Pro", price_monthly: 20, price_annual: 192, features: ["500 fast requests/mo", "Unlimited slow requests", "GPT-4, Claude 3.5"], limits: "500 fast requests" }, { name: "Business", price_monthly: 40, price_annual: 384, features: ["Unlimited fast requests", "Team features", "Admin dashboard"], limits: "Unlimited" }, { name: "Enterprise", price_monthly: 80, price_annual: 768, features: ["SSO", "Advanced security", "Custom contracts"], limits: "Unlimited" }], free_tier_available: true, pay_as_you_go: false, api_pricing_note: "Per-seat pricing" },
  { tool_id: "windsurf", name: "Windsurf", category: "coding", url: "https://windsurf.com", tiers: [{ name: "Pro", price_monthly: 15, price_annual: 144, features: ["AI coding assistant", "Context-aware edits"], limits: "Individual usage" }, { name: "Teams", price_monthly: 30, price_annual: 300, features: ["Team workspace", "Admin controls"], limits: "Team usage" }, { name: "Enterprise", price_monthly: 60, price_annual: 600, features: ["SSO", "Advanced security"], limits: "Custom" }], free_tier_available: false, pay_as_you_go: false, api_pricing_note: "Per-seat pricing seed" },
  { tool_id: "github_copilot", name: "GitHub Copilot", category: "coding", url: "https://github.com/features/copilot", tiers: [{ name: "Individual", price_monthly: 10, price_annual: 100, features: ["Code suggestions", "Chat", "CLI"], limits: "Unlimited" }, { name: "Business", price_monthly: 19, price_annual: 190, features: ["Team features", "Knowledge base", "Admin dashboard"], limits: "Unlimited" }, { name: "Enterprise", price_monthly: 39, price_annual: 390, features: ["SSO", "Advanced security", "Audit logs"], limits: "Unlimited" }], free_tier_available: false, pay_as_you_go: false, api_pricing_note: "Per-seat pricing" },
  { tool_id: "claude", name: "Claude", category: "chat", url: "https://claude.ai", tiers: [{ name: "Free", price_monthly: 0, price_annual: 0, features: ["Basic Claude chat access"], limits: "Limited usage" }, { name: "Pro", price_monthly: 20, price_annual: 200, features: ["5x more usage", "Priority access", "Early features"], limits: "5x more than free" }, { name: "Max", price_monthly: 100, price_annual: 1200, features: ["Higher usage limits", "Priority access"], limits: "Heavy individual usage" }, { name: "Team", price_monthly: 30, price_annual: 300, features: ["Team workspace", "Shared billing", "Admin controls"], limits: "Unlimited" }, { name: "Enterprise", price_monthly: 60, price_annual: 600, features: ["SSO", "Security reviews", "Central administration"], limits: "Custom" }, { name: "API direct", price_monthly: 0, features: ["Usage-based Anthropic API access"], limits: "Usage-based" }], free_tier_available: true, pay_as_you_go: false },
  { tool_id: "chatgpt", name: "ChatGPT", category: "chat", url: "https://chatgpt.com", tiers: [{ name: "Plus", price_monthly: 20, price_annual: 199, features: ["GPT-4o", "DALL-E", "Browse", "Plugins"], limits: "Unlimited" }, { name: "Team", price_monthly: 30, price_annual: 299, features: ["Team workspace", "Admin console", "Custom GPTs"], limits: "Unlimited" }, { name: "Enterprise", price_monthly: 60, price_annual: 599, features: ["SSO", "Analytics", "Priority support"], limits: "Unlimited" }, { name: "API direct", price_monthly: 0, features: ["Usage-based OpenAI API access"], limits: "Usage-based" }], free_tier_available: true, pay_as_you_go: false },
  { tool_id: "anthropic_api", name: "Anthropic API", category: "api", url: "https://www.anthropic.com/api", tiers: [{ name: "API direct", price_monthly: 0, features: ["Usage-based Claude API access", "No seat commitment"], limits: "Usage-based" }], free_tier_available: false, pay_as_you_go: true, api_pricing_note: "Usage-based Anthropic API spend" },
  { tool_id: "gemini", name: "Gemini", category: "chat", url: "https://gemini.google.com", tiers: [{ name: "Pro", price_monthly: 19.99, price_annual: 199.99, features: ["Gemini app access", "Google AI features"], limits: "Individual usage" }, { name: "Ultra", price_monthly: 249.99, price_annual: 2999.88, features: ["Highest-tier Gemini access", "Advanced Google AI features"], limits: "Heavy individual usage" }, { name: "API", price_monthly: 0, features: ["Usage-based Gemini API access"], limits: "Usage-based" }], free_tier_available: true, pay_as_you_go: false },
  { tool_id: "openai_api", name: "OpenAI API", category: "api", url: "https://openai.com/api", tiers: [{ name: "API direct", price_monthly: 0, features: ["Per-token pricing", "No commitment"], limits: "Usage-based" }], free_tier_available: true, pay_as_you_go: true, api_pricing_note: "Usage-based OpenAI API spend" },
  { tool_id: "perplexity", name: "Perplexity", category: "chat", url: "https://perplexity.ai", tiers: [{ name: "Pro", price_monthly: 20, price_annual: 200, features: ["Copilot", "Claude/GPT-4", "API access"], limits: "600 Copilot searches/day" }, { name: "Enterprise", price_monthly: 50, price_annual: 500, features: ["SSO", "Priority support", "Custom integrations"], limits: "Unlimited" }], free_tier_available: true, pay_as_you_go: false },
  { tool_id: "midjourney", name: "Midjourney", category: "other", url: "https://midjourney.com", tiers: [{ name: "Basic", price_monthly: 10, price_annual: 96, features: ["3.3 GPU hours/mo", "Commercial use"], limits: "3.3 GPU hours" }, { name: "Standard", price_monthly: 30, price_annual: 288, features: ["15 GPU hours/mo", "Stealth mode"], limits: "15 GPU hours" }, { name: "Pro", price_monthly: 60, price_annual: 576, features: ["30 GPU hours/mo", "Stealth mode", "Private mode"], limits: "30 GPU hours" }, { name: "Mega", price_monthly: 120, price_annual: 1152, features: ["60 GPU hours/mo", "All features"], limits: "60 GPU hours" }], free_tier_available: false, pay_as_you_go: false },
  { tool_id: "runway", name: "Runway", category: "other", url: "https://runwayml.com", tiers: [{ name: "Standard", price_monthly: 12, price_annual: 132, features: ["625 credits/mo", "Gen-3 Alpha"], limits: "625 credits" }, { name: "Unlimited", price_monthly: 28, price_annual: 308, features: ["Unlimited generations", "Priority processing"], limits: "Unlimited" }, { name: "Enterprise", price_monthly: 75, price_annual: 825, features: ["Custom credits", "SSO", "Dedicated support"], limits: "Custom" }], free_tier_available: false, pay_as_you_go: false },
];

export function getPricingDatabase(): ToolPricing[] {
  return PRICING_DATABASE;
}

export function getToolPricing(toolId: string): ToolPricing | undefined {
  return PRICING_DATABASE.find((tool) => tool.tool_id === toolId);
}
